include:
  - component: gitlab.com/Northern.tech/Mender/mendertesting/commit-lint@master
  - project: 'Northern.tech/Mender/mendertesting'
    file:
      - '.gitlab-ci-github-status-updates.yml'
      - '.gitlab-ci-check-license.yml'
  - component: gitlab.com/Northern.tech/Mender/mendertesting/renovate@master
    inputs:
      stage: "renovate"

stages:
  - renovate
